"""Verify the Excel templates generated by ``build_checklist_templates.py``.

Checks:

* All nine expected files exist under ``assessment/templates/``.
* Each file loads as a valid OOXML ``.xlsx`` workbook (not a DRM/OLE2
  sensitivity-labelled file).
* Column headers match the expected schema.
* Row counts match the filter derived from the manifest.

Exits 0 on success, 1 otherwise.
"""
from __future__ import annotations

import json
import re
import sys
import zipfile
from pathlib import Path

from openpyxl import load_workbook

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST = REPO_ROOT / "assessment" / "manifest" / "controls.json"
TEMPLATES_DIR = REPO_ROOT / "assessment" / "templates"

CHECKLIST_HEADERS = [
    "Control ID", "Title", "Pillar", "Tier", "Surface(s)",
    "Question", "Evidence Expected", "Yes/Partial/No", "Notes",
]
DASHBOARD_HEADERS = [
    "Control ID", "Title", "Pillar", "Surface",
    "Baseline yes-bar", "Recommended yes-bar", "Regulated yes-bar",
    "Status", "Score",
]

# Roles mirrored from build_checklist_templates.ROLE_FILES. Keep in sync.
ROLE_FILES = [
    ("ai-administrator-checklist.xlsx", "AI Governance Lead"),
    ("m365-global-admin-or-copilot-admin-checklist.xlsx", "M365 Global Admin"),
    ("entra-global-admin-checklist.xlsx", "Entra Global Admin"),
    ("sharepoint-admin-checklist.xlsx", "SharePoint Admin"),
    ("purview-compliance-admin-checklist.xlsx", "Purview Compliance Admin"),
    ("teams-admin-checklist.xlsx", "Teams Admin"),
    ("security-admin-checklist.xlsx", "Security Admin"),
    ("compliance-officer-checklist.xlsx", None),  # hardcoded fallback
]

COMPLIANCE_OFFICER_IDS = {
    "1.10", "1.12", "2.1", "2.2", "2.10",
    "3.1", "3.2", "3.3", "3.4", "3.5", "3.6", "3.7",
    "3.8", "3.9", "3.10", "3.11", "3.12", "3.13",
}


def header_row_index(ws) -> int:
    """Find the row where 'Control ID' appears in column A."""
    for row in range(1, 20):
        cell = ws.cell(row=row, column=1).value
        if cell and str(cell).strip() == "Control ID":
            return row
    raise AssertionError("'Control ID' header not found in first 20 rows")


def read_headers(ws, header_row: int, count: int) -> list[str]:
    return [str(ws.cell(row=header_row, column=i + 1).value or "").strip()
            for i in range(count)]


def count_control_rows(ws, header_row: int) -> int:
    n = 0
    for row in range(header_row + 1, ws.max_row + 1):
        cid = ws.cell(row=row, column=1).value
        if cid is None:
            continue
        s = str(cid).strip()
        parts = s.split(".")
        if len(parts) == 2 and parts[0].isdigit() and re.match(r"^\d+[a-z]?$", parts[1]):
            n += 1
    return n


def expected_counts(manifest: list[dict]) -> dict[str, int]:
    role_to_ids: dict[str, list[str]] = {}
    for c in manifest:
        for r in c.get("roles") or []:
            role_to_ids.setdefault(r, []).append(c["id"])
    all_ids = {c["id"] for c in manifest}

    counts: dict[str, int] = {}
    for filename, manifest_role in ROLE_FILES:
        if manifest_role and role_to_ids.get(manifest_role):
            counts[filename] = len(role_to_ids[manifest_role])
        else:
            counts[filename] = len(COMPLIANCE_OFFICER_IDS & all_ids)
    counts["governance-maturity-dashboard.xlsx"] = len(manifest)
    return counts


def verify_file(path: Path, expected_count: int,
                is_dashboard: bool) -> list[str]:
    errs: list[str] = []
    if not path.exists():
        return [f"missing file: {path}"]
    if not zipfile.is_zipfile(path):
        return [f"{path.name}: not a valid OOXML (.xlsx) — possibly "
                "DRM/sensitivity-labelled"]

    try:
        wb = load_workbook(path, data_only=False)
    except Exception as exc:  # pragma: no cover
        return [f"{path.name}: failed to open ({exc})"]

    ws = wb.active
    header_row = header_row_index(ws)

    expected_headers = (DASHBOARD_HEADERS if is_dashboard
                        else CHECKLIST_HEADERS)
    actual = read_headers(ws, header_row, len(expected_headers))
    if actual != expected_headers:
        errs.append(
            f"{path.name}: header mismatch\n    expected {expected_headers}\n"
            f"    actual   {actual}")

    n = count_control_rows(ws, header_row)
    if n != expected_count:
        errs.append(f"{path.name}: expected {expected_count} control rows, "
                    f"found {n}")

    wb.close()
    return errs


def main() -> int:
    if not TEMPLATES_DIR.exists():
        print(f"[FAIL] templates dir missing: {TEMPLATES_DIR}")
        return 1
    with MANIFEST.open("r", encoding="utf-8") as fh:
        manifest = json.load(fh)
    counts = expected_counts(manifest)

    errors: list[str] = []
    for filename, expected in counts.items():
        is_dash = filename == "governance-maturity-dashboard.xlsx"
        path = TEMPLATES_DIR / filename
        file_errs = verify_file(path, expected, is_dash)
        if file_errs:
            errors.extend(file_errs)
        else:
            print(f"[PASS] {filename} ({expected} controls)")

    if errors:
        print()
        print("[FAIL] Excel template verification failed:")
        for err in errors:
            print(f"  - {err}")
        return 1
    print(f"\n[PASS] All {len(counts)} Excel templates verified.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
