"""Verify checklist workbooks generated by ``build_checklist_templates.py``.

Checks:

* Expected workbooks exist under both template directories.
* All ``.xlsx`` files are valid OOXML ZIP containers (placeholder text fails).
* Column headers and row counts match generated-role filters from the manifest.
* Required control IDs for supervision/records coverage are present per role.
"""
from __future__ import annotations

import json
import re
import sys
import zipfile
from pathlib import Path

from openpyxl import load_workbook

from build_checklist_templates import (  # keep schema/counts aligned to builder
    ROLE_FILES,
    build_role_to_ids,
    select_ids,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST = REPO_ROOT / "assessment" / "manifest" / "controls.json"
TEMPLATE_DIRS = [
    REPO_ROOT / "assessment" / "templates",
    REPO_ROOT / "docs" / "assessment" / "templates",
]

CHECKLIST_HEADERS = [
    "Control ID", "Title", "Pillar", "Tier", "Surface(s)",
    "Question", "Evidence Expected", "Yes/Partial/No", "Notes",
]
DASHBOARD_HEADERS = [
    "Control ID", "Title", "Pillar", "Surface",
    "Baseline yes-bar", "Recommended yes-bar", "Regulated yes-bar",
    "Status", "Score",
]

REQUIRED_ROLE_CONTROL_IDS = {
    "compliance-officer-checklist.xlsx": {"3.8a", "3.14", "4.15", "4.16"},
    "purview-compliance-admin-checklist.xlsx": {"3.8a", "3.14", "4.16"},
    "records-manager-checklist.xlsx": {"3.14", "4.15", "4.16"},
}


def header_row_index(ws) -> int:
    """Find the row where 'Control ID' appears in column A."""
    for row in range(1, 20):
        cell = ws.cell(row=row, column=1).value
        if cell and str(cell).strip() == "Control ID":
            return row
    raise AssertionError("'Control ID' header not found in first 20 rows")


def read_headers(ws, header_row: int, count: int) -> list[str]:
    return [str(ws.cell(row=header_row, column=i + 1).value or "").strip()
            for i in range(count)]


def collect_control_ids(ws, header_row: int) -> set[str]:
    ids: set[str] = set()
    for row in range(header_row + 1, ws.max_row + 1):
        cid = ws.cell(row=row, column=1).value
        if cid is None:
            continue
        s = str(cid).strip()
        parts = s.split(".")
        if len(parts) == 2 and parts[0].isdigit() and re.match(r"^\d+[a-z]?$", parts[1]):
            ids.add(s)
    return ids


def expected_counts(manifest: list[dict]) -> dict[str, int]:
    role_to_ids = build_role_to_ids(manifest)
    all_ids = [c["id"] for c in manifest]
    counts: dict[str, int] = {}
    for filename, _role_label, manifest_role in ROLE_FILES:
        counts[filename] = len(select_ids(filename, manifest_role, role_to_ids, all_ids))
    counts["governance-maturity-dashboard.xlsx"] = len(manifest)
    return counts


def verify_file(path: Path, expected_count: int, is_dashboard: bool,
                required_ids: set[str] | None = None) -> list[str]:
    errs: list[str] = []
    if not path.exists():
        return [f"missing file: {path}"]
    if not zipfile.is_zipfile(path):
        return [f"{path.name}: not a valid OOXML (.xlsx) — possibly "
                "DRM/sensitivity-labelled or placeholder text"]

    try:
        wb = load_workbook(path, data_only=False)
    except Exception as exc:  # pragma: no cover
        return [f"{path.name}: failed to open ({exc})"]

    ws = wb.active
    header_row = header_row_index(ws)

    expected_headers = DASHBOARD_HEADERS if is_dashboard else CHECKLIST_HEADERS
    actual = read_headers(ws, header_row, len(expected_headers))
    if actual != expected_headers:
        errs.append(
            f"{path.name}: header mismatch\n    expected {expected_headers}\n"
            f"    actual   {actual}")

    control_ids = collect_control_ids(ws, header_row)
    if len(control_ids) != expected_count:
        errs.append(f"{path.name}: expected {expected_count} control rows, "
                    f"found {len(control_ids)}")

    if not is_dashboard and required_ids:
        missing = sorted(required_ids - control_ids)
        if missing:
            errs.append(
                f"{path.name}: missing required control IDs {missing}"
            )

    wb.close()
    return errs


def main() -> int:
    with MANIFEST.open("r", encoding="utf-8") as fh:
        manifest = json.load(fh)
    counts = expected_counts(manifest)
    expected_filenames = set(counts.keys())

    errors: list[str] = []
    for templates_dir in TEMPLATE_DIRS:
        if not templates_dir.exists():
            errors.append(f"templates dir missing: {templates_dir}")
            continue

        xlsx_files = sorted(templates_dir.glob("*.xlsx"))
        actual_filenames = {p.name for p in xlsx_files}
        missing = sorted(expected_filenames - actual_filenames)
        unexpected = sorted(actual_filenames - expected_filenames)
        if missing:
            errors.append(f"{templates_dir}: missing expected templates {missing}")
        if unexpected:
            errors.append(f"{templates_dir}: unexpected templates {unexpected}")

        for path in xlsx_files:
            if not zipfile.is_zipfile(path):
                errors.append(
                    f"{templates_dir.name}\\{path.name}: not a valid OOXML "
                    "(.xlsx) container"
                )

        for filename, expected in counts.items():
            is_dash = filename == "governance-maturity-dashboard.xlsx"
            required_ids = REQUIRED_ROLE_CONTROL_IDS.get(filename)
            path = templates_dir / filename
            file_errs = verify_file(path, expected, is_dash, required_ids)
            if file_errs:
                errors.extend(f"{templates_dir.name}\\{msg}" for msg in file_errs)
            else:
                print(
                    f"[PASS] {templates_dir.name}\\{filename} "
                    f"({expected} controls)"
                )

    if errors:
        print()
        print("[FAIL] Excel template verification failed:")
        for err in errors:
            print(f"  - {err}")
        return 1
    print(f"\n[PASS] All {len(counts)} templates verified in both directories.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
